### ISSUE TITLE
Image on Hub vs on spokes.yaml

### ISSUE THREAD

**Issue by iranzo** [rh-ecosystem-edge/ztp-pipeline-relocatable#108]
Check:

![image](https://user-images.githubusercontent.com/312463/158216724-70b21996-57c3-4139-8c05-95e66947afef.png)

**Comment by iranzo** [comment]
I think that this is already solved in current main branch.

@alknopfler ?

**Comment by alknopfler** [comment]
@iranzo yes, it's solved
