### ISSUE TITLE
Create edgeadmin user during flow

### ISSUE THREAD

**Issue by iranzo** [rh-ecosystem-edge/ztp-pipeline-relocatable#120]

**Comment by fbac** [comment]
currently and by default, we create:
- kubeadmin for auth with password
- kubeconfig for system:admin, auth by certs
- a csr-approver-ztpfw is created to ensure validity of all node's certificates and injected into a systemd service

what would be the purpose of edgeadmin that we can't currently achieve with the users that already exists?
