### ISSUE TITLE
Plugable approach for ignition

### ISSUE THREAD

**Issue by iranzo** [rh-ecosystem-edge/ztp-pipeline-relocatable#168]
Currently in render_spokes, we generate an ignition file that will be used to deploy the csr approver. 

We should evolve it to be a plugable system not just for csr-approver but for other scripts that might be needed in the future, and probably having each one of them one copy of the kubeconfig if needed that can be used and removed independently

**Comment by fbac** [comment]
+1, this is definitely useful.

But we have to keep in mind:
- use cases, what would be an use case for this?
    - will admins at the factory be able to inject ignitions at edge install time?
    - will it be only an internal feature to ship with the factory operator/installer? (only for us - developers)
- OCP supportability
    - not all changes via ignition are supported as of today
