### ISSUE TITLE
Reduce 120 secs wait in the worker agent script

### ISSUE THREAD

**Issue by iranzo** [rh-ecosystem-edge/ztp-pipeline-relocatable#312]
As part of the merge of https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable/pull/229, a sleep 120 was put in place to give enough time for the resource to be created as before, the variable was not filled and the code failed.

In the line of that PR, we should improve the 'sleep $RANDOM' to actually become some function to wait for required resources to be processed and appear in oc commands, and from there, wait for the desired status before continuing without having to write loops that control them.

The 'patch' that raised this issue as technical debt is this line: https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable/blob/main/deploy-worker/render_worker.sh#L159 but should be applicable in other pieces of the code

**Comment by fbac** [comment]
PTAL @iranzo, could you please ellaborate? So somebody can jump on this one.

Thanks!

**Comment by iranzo** [comment]
Closed via bf105c9f40b65e794894d90782ffcb7503ae445f
