### ISSUE TITLE
Name change from edgecluster to edge

### ISSUE THREAD

**Issue by fbac** [rh-ecosystem-edge/ztp-pipeline-relocatable#359]
Opening the discussion here before moving forward with the development.

Recently the name convention changed from spoke to edgecluster, the reasoning behind re-opening this topic is that edgecluster seems a bit 'off' since it create resources like 'edgecluster0-cluster'.

Shall we discuss the change from edgecluster to simply 'edge', so the resources are a bit more readable and less redundant, such as edge-deployer, edgeX-cluster?

PTAL @flaper87 @iranzo

**Comment by flaper87** [comment]
@fbac counter proposal. We remvoe the `-cluster` suffix [from here](https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable/blob/9ee5dfeba5a8a140d8281cd4a63bc1cad325a102/hack/deploy-hub-local/build-edgecluster.sh#L112). I think not having hard-coded parameters would be better.

Also, I think this only affect us when using the `build-edgecluster.sh` scripts. It shouldn't affect other environments. Am I missing something?

**Comment by fbac** [comment]
@flaper87 that indeed would introduce less noise.

The files that would be affected by that change are:
```
.github/workflows/testing-pr.yml
deploy-edgecluster/render_edgecluster.sh
hack/env
hack/deploy-hub-local/build-egecluster.sh
hack/deploy-hub-local/create-vm.yml
hack/deploy-hub-local/create-vm-sno.yml
hack/deploy-hub-local/lab-dns-internal.sh
hack/deploy-hub-local/lab-dns-external.sh
hack/deploy-hub-local/ansible/tasks/files
```

We can always modify these and run a couple test to be sure the change is a success.

**Comment by fbac** [comment]
Closing this issue as the work will be done in https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable/issues/356

As a part of the renaming of the internal domain to factory.local, we'll use the change and tests to delete the trailing -cluster, sanitizing the whole naming scheme at once.

PTAL @iranzo
