### ISSUE TITLE
MCO Monitoring run's indefinitely

### ISSUE THREAD

**Issue by eifrach** [rh-ecosystem-edge/ztp-pipeline-relocatable#376]
on some case's, the MCO is restarted before the loop find's that the API is down

need to improve this check by checking if the update is already completed and give it a timeout.

```shell
# shared-utils/wait_for_sno_mco.sh

while [ ${retry} != 0 ]; do
    oc --kubeconfig=${KUBECONFIG} get nodes &>/dev/null
    if [[ $? == 0 ]]; then
        echo "$(tput setab 7)$(tput setaf 4)[ZTPFW - Monitoring MCO - SNO]$(tput sgr 0) >>>> API is up...waiting until mco will restart the node"
        sleep 10
        retry=$((retry + 1))
    else
        echo "$(tput setab 7)$(tput setaf 4)[ZTPFW - Monitoring MCO - SNO]$(tput sgr 0) >>>> API is down...The Cluster is restarting"
        retry=0
    fi
done
 
```

**Comment by alknopfler** [comment]
The script works fine...
The problem will appears only if you re-run the pipeline (due to a failure in the pipe steps) without stop the script for any reason...
in this case, the script should be stopped and re-launched again.
With the happy path is working fine...

Is it worth fixing in this case?

**Comment by alknopfler** [comment]
after talking with @eifrach we will add a previous timeout just to ensure at the end of the first loop api is not from another re-run
