### ISSUE TITLE
change sed to use envsub

### ISSUE THREAD

**Issue by alknopfler** [rh-ecosystem-edge/ztp-pipeline-relocatable#4]
during the first steps of the pipeline, we've used sed to replace variables and placesholder, which will be changed to use kustomize and envsub

**Comment by iranzo** [comment]
Related with #7

**Comment by iranzo** [comment]
From quick search using 'grep', it might involve touching:

deploy-acm/deploy.sh
deploy-disconnected-registry/olm-sync.sh
deploy-disconnected-registry/verify_olm_sync.sh
deploy-httpd-server/deploy.sh
deploy-hub-configs/deploy.sh
hack/deploy-hub-local/00_virtual.sh.ipmi
hack/deploy-hub-local/00_virtual.sh.redfish
hack/deploy-hub-local/05_cache.sh
hack/deploy-hub-local/06_disconnected.sh
hack/deploy-hub-local/build.sh
hack/deploy-hub-local/deploy.sh
hack/deploy-hub-local/helpers/extras.sh
hack/deploy-hub-local/helpers/pull_and_push.sh
hack/deploy-hub-local/helpers/sushy.py
hack/deploy-hub-local/Jenkinsfile
hack/deploy-hub-local/Jenkinsfile.ocp
hack/deploy-hub-local/kcli_default.yml
hack/deploy-hub-local/notify.sh
hack/deploy-hub-local/README.md
shared-utils/verify_preflight.sh
