### ISSUE TITLE
Preflight PV Check for SNO Hub deployment fails

### ISSUE THREAD

**Issue by schmti** [rh-ecosystem-edge/ztp-pipeline-relocatable#521]
https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable/blob/2fd9aec8e153cb249d2f6fa36b6407f1c6a93917/shared-utils/verify_preflight.sh#L123

Hello all,

we found an issue in the pipeline (deploy-ztp-hub) in our enviroment. 

The following step fails on our enviroment in the preflight steps:
 >>>> Verify the PV available
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Error: Persistent volumes not available in the hub

The command "oc get pv | wc -l" evaluated to '2' in our enviroment so the pipeline fails.

Our workaround just add a dummy PV in our enviroment, but maybe concider the value changing from 3 to 2. Or refactor the test.

Greets,
schmti

**Comment by alknopfler** [comment]
Hi, 
The test is OK we need at least 3 pv available but in some use cases we need up to 5-6
`$ oc get pv
NAME    CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                                             STORAGECLASS   REASON   AGE
pv001   200Gi      RWO            Recycle          Bound       multicluster-engine/assisted-service                                      15d
pv002   200Gi      RWO            Recycle          Bound       open-cluster-management/search-redisgraph-pvc-0                           15d
pv003   200Gi      RWO            Recycle          Bound       edgecluster-deployer/ztp-pvc                                              15d
pv004   200Gi      RWO            Recycle          Available                                                                             15d
pv005   200Gi      RWO            Recycle          Available                                                                             15d
pv006   200Gi      RWO            Recycle          Bound       default/httpd-pv-claim                                                    15d
pv007   200Gi      RWO            Recycle          Bound       ztpfw-registry/data-pvc                                                   15d
pv008   200Gi      RWO            Recycle          Available                                                                             15d
pv009   200Gi      RWO            Recycle          Bound       multicluster-engine/postgres                                              15d
pv010   200Gi      RWO            Recycle          Available                                                                             15d`

**Comment by alknopfler** [comment]
if you're just using 2, the pipeline will fail

**Comment by schmti** [comment]
We use dynamic provisioning for our PVs. The Cluster have a "default" StorageClass. In addtion we add more Operators for the mirroring so we need bigger PVs and PVCs.
