### ISSUE TITLE
Issue in grab_node_ext_ips (shared-utils)

### ISSUE THREAD

**Issue by schmti** [rh-ecosystem-edge/ztp-pipeline-relocatable#847]
Found an issue here:

The task "deploy-metallb" always failed for us because the node_ip could not be determined correctly. 

For our DHCP network we have the network 192.168.70.0/24. 

In the line here: [https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable/blob/main/shared-utils/common.sh#L364C185-L364C185](url)

the part "| select(. | contains(\"192.168.**7**\") | not)" ensures that the networks:

192.168.7[0..9].0/XX are also sorted out. The addition of a point settles the issue:

"| select(. | contains(\"192.168.**7.**\") | not)". 

Resolution
$ oc get agent xxxxx-xxxxxxx-xxxxxxx-xxxxxxxxxx  --no-headers -ojson -n line-138-v12 | jq -r "(.status.inventory.interfaces[] | select(.name==\"eno1\")).ipV4Addresses[] | select(. | contains(\"192.168.7\") | not)"
--> no output
$ oc get agent xxxxx-xxxxxxx-xxxxxxx-xxxxxxxxxx--no-headers -ojson -n line-138-v12 | jq -r "(.status.inventory.interfaces[] | select(.name==\"eno1\")).ipV4Addresses[] | select(. | contains(\"192.168.7.\") | not)"
--> 192.168.70.27/24 (NodeIP)

**Comment by jhernand** [comment]
@schmti you suggestion to fix this issue looks reasonable to me. Would you be so kind to submit a pull request with the fix? I would happily review and merge it.

**Comment by schmti** [comment]
@jhernand on which branch do you want the MR? 
greets

**Comment by jhernand** [comment]
> @jhernand on which branch do you want the MR? greets

In the `main` branch, please.
