### ISSUE TITLE
blkdiscard --> Operation not permitted

### ISSUE THREAD

**Issue by schmti** [rh-ecosystem-edge/ztp-pipeline-relocatable#848]
Wiping edge disks fails on our hardware stack:
---> Wipe storage disks for Master 0 Node
Master Node: 0
AGENT: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx
IP: 192.168.70.27
---> 
---> Wipe disk /dev/sda at 0 192.168.70.27
Creating new GPT entries.
GPT data structures destroyed! You may now partition the disk using fdisk or
other utilities.
100+0 records in
100+0 records out
104857600 bytes (105 MB, 100 MiB) copied, 0.158316 s, 662 MB/s
blkdiscard: /dev/sda: BLKDISCARD ioctl failed: Operation not supported

Changed command here:
`https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable/blob/main/shared-utils/common.sh#L338C42-L338C42`

${SSH_COMMAND} -i ${RSA_KEY_FILE} core@${NODE_IP} "sudo sgdisk --zap-all $disk;sudo dd if=/dev/zero of=$disk bs=1M count=100 oflag=direct,dsync; sudo blkdiscard $disk"
to:
${SSH_COMMAND} -i ${RSA_KEY_FILE} core@${NODE_IP%%/*} "sudo wipefs --all --force $disk;"

No it works (a command which is more compatible with all hardware stacks)

**Comment by schmti** [comment]
@jhernand yes sure. On which branch you want the MR?

**Comment by jhernand** [comment]
> @jhernand yes sure. On which branch you want the MR?

In the `main` branch.
