### ISSUE TITLE
ERROR - ztpfw-ui 

### ISSUE THREAD

**Issue by schmti** [rh-ecosystem-edge/ztp-pipeline-relocatable#851]
During the network migration, the new addresses could not be set in the GUI. 
GUI --> "Resource update failed - Can not update ingress-public-ip AddressPool in the metallb namespace"
              -->The chrome debug console gave output: 'resource not found' 

After investigations, there is a drift between the APIVersions:
[Frontend Constants](https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable/blob/main/ui/frontend/src/components/PersistPage/resourceTemplates.ts#L11C1-L11C1)
apiVersion: 'metallb.io/v1alpha1',
kind: 'AddressPool',

But in metallb other APIVersions are used:
[MetalLB deployment](https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable/blob/main/deploy-metallb/manifests/address_pool.yaml#L2)
apiVersion: metallb.io/v1beta1
kind: IPAddressPool

So our deliveries will not work with the GUI. Only with kubeadmin and manual patches.

**Comment by jhernand** [comment]
This is a known issue, should be at least partially addressed by #827. But work on the UI stopped quite some time ago and we have currently no plans to resume it.
